use_frameworks!

def anyone
  pod 'AnyoneKit',
#    :git => 'https://github.com/anyone-protocol/AnyoneKit.git'
    :path => '../'
end


target 'AnyoneKit-Example' do
  platform :ios, '15.0'

  anyone

  target 'AnyoneKit-Tests' do
    inherit! :search_paths
  end

end

target 'AnyoneKit-Example-Mac' do
  platform :macos, '11.0'

  anyone
end
