use_frameworks!

def anyone
  pod 'AnyoneKit', :path => '../'
end


target 'AnyoneKit-Example' do
  platform :ios, '12.0'

  anyone

  target 'AnyoneKit-Tests' do
    inherit! :search_paths
  end

end

target 'AnyoneKit-Example-Mac' do
  platform :macos, '10.13'

  anyone
end
